sonar.projectKey=flappy-fun
sonar.projectName=flappy-fun
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.ts,src/test/**/*.test.tsx
sonar.exclusions=dist/**,node_modules/**,public/**,coverage/**,playwright-report/**,test-results/**
sonar.typescript.tsconfigPath=tsconfig.json
