apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flappy-fun
  namespace: flappy-fun-dev
  labels:
    app.kubernetes.io/name: flappy-fun
    app.kubernetes.io/environment: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flappy-fun
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
